---
name: realrec
mysqlBatchSize: 10
mysqlWaitMillis: 10000
metadataHosts: 127.0.0.1:5587
metadataConns: 8
metadataThreads: 4
hashCacheHours: 6
detailCacheHours: 6
myrrixHost: localhost
myrrixPort: 8080